# Generated by Django 5.1.6 on 2025-03-01 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('status', models.CharField(choices=[('todo', '진행 전'), ('in_progress', '진행 중'), ('done', '완료')], default='todo', max_length=20, verbose_name='상태')),
                ('priority', models.IntegerField(default=0, verbose_name='우선순위')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='마감일')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '업무',
                'verbose_name_plural': '업무',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
